import { ArrowRight, BadgeCheck, CalendarCheck2, CheckCircle2, ChevronRight, ClipboardCheck, Clock3, Drill, Hammer, Lightbulb, MapPin, Phone, PlugZap, Quote, ShieldCheck, Star, Wrench } from 'lucide-react'
import { Link } from 'react-router-dom'
import { PublicHeader } from '../components/PublicHeader'

const services = [
  { icon: <Wrench />, title: 'Plumbing repairs', text: 'Leaks, blocked drains, taps and small installations.', tone: 'blue' },
  { icon: <PlugZap />, title: 'Electrical help', text: 'Sockets, lighting, switches and fault checks.', tone: 'yellow' },
  { icon: <Drill />, title: 'Furniture assembly', text: 'Wardrobes, desks, shelving and wall mounting.', tone: 'green' },
  { icon: <Hammer />, title: 'Small renovations', text: 'Painting, patching, tiling and finishing work.', tone: 'orange' },
]

export function LandingPage() {
  return (
    <div className="public-page">
      <PublicHeader />
      <main>
        <section className="hero">
          <div className="container hero-grid">
            <div className="hero-copy"><span className="eyebrow"><i /> TRUSTED HOME REPAIR IN PRAGUE</span><h1>Your home, fixed<br /><em>without the fuss.</em></h1><p>Reliable local technicians for the repairs and small jobs that keep your home running smoothly.</p><div className="hero-actions"><Link className="button button-primary" to="/request">Request a repair <ArrowRight size={18} /></Link><a className="phone-link" href="tel:+420212345678"><Phone size={20} /><span><small>Prefer to call?</small><strong>+420 212 345 678</strong></span></a></div><div className="hero-proof"><span><CheckCircle2 /> Clear upfront pricing</span><span><CheckCircle2 /> Vetted technicians</span><span><CheckCircle2 /> Prague-wide service</span></div></div>
            <div className="hero-visual" aria-label="Home repair service overview"><div className="house-scene"><div className="house-roof" /><div className="house-body"><span className="window one" /><span className="window two" /><span className="door" /></div><div className="scene-tools"><span><Wrench /></span><span><Drill /></span><span><Lightbulb /></span></div></div><div className="floating-card rating-card"><span className="rating-icon"><Star fill="currentColor" /></span><span><strong>4.9 / 5</strong><small>from 240+ local jobs</small></span></div><div className="floating-card availability-card"><span><i /> Available today</span><strong>Next slot: 14:30</strong></div></div>
          </div>
        </section>
        <section className="signal-strip"><div className="container"><span><ShieldCheck /><strong>12-month</strong><small>workmanship guarantee</small></span><span><Clock3 /><strong>30 min</strong><small>average response time</small></span><span><MapPin /><strong>All Prague</strong><small>and nearby districts</small></span><span><BadgeCheck /><strong>Verified</strong><small>local professionals</small></span></div></section>
        <section className="section services-section" id="services"><div className="container"><div className="section-heading"><div><span className="eyebrow">WHAT WE CAN HELP WITH</span><h2>One team for the jobs<br />around your home.</h2></div><p>From the urgent fix to the job that has been waiting for months, tell us what you need and we'll match the right person.</p></div><div className="service-grid">{services.map((service) => <article className="service-card" key={service.title}><span className={`service-icon ${service.tone}`}>{service.icon}</span><h3>{service.title}</h3><p>{service.text}</p><Link to="/request">Request this service <ChevronRight size={17} /></Link></article>)}</div><div className="services-note">Don't see your job listed? <Link to="/request">Tell us what you need →</Link></div></div></section>
        <section className="section process-section" id="process"><div className="container process-grid"><div className="process-copy"><span className="eyebrow light">SIMPLE FROM START TO FINISH</span><h2>A repair shouldn't create more work.</h2><p>We keep the process clear, from your first message to a finished job.</p><Link className="button button-light" to="/request">Get started <ArrowRight size={18} /></Link></div><div className="process-steps"><article><span>01</span><div className="step-icon"><ClipboardCheck /></div><h3>Describe the job</h3><p>Send the details, your location and a preferred time.</p></article><article><span>02</span><div className="step-icon"><CalendarCheck2 /></div><h3>We confirm the plan</h3><p>We'll clarify the scope and agree on timing and price.</p></article><article><span>03</span><div className="step-icon"><CheckCircle2 /></div><h3>Consider it handled</h3><p>A vetted technician completes the work and cleans up.</p></article></div></div></section>
        <section className="section reviews-section" id="reviews"><div className="container"><div className="review-card"><Quote /><div className="stars">★★★★★</div><blockquote>“The request took two minutes, the plumber arrived the same afternoon, and the price was exactly what we agreed. Genuinely easy.”</blockquote><div className="reviewer"><span>KN</span><div><strong>Klára Novotná</strong><small>Prague 6 · Plumbing repair</small></div></div></div><div className="review-copy"><span className="eyebrow">LOCAL, PRACTICAL, RELIABLE</span><h2>The small-job team<br />you can count on.</h2><p>Prague HomeFix is a fictional service company created to demonstrate the complete FlowLead CRM customer journey.</p><ul><li><CheckCircle2 /> Clear communication</li><li><CheckCircle2 /> Respect for your home</li><li><CheckCircle2 /> No surprise charges</li></ul></div></div></section>
        <section className="cta-section"><div className="container"><div><span className="eyebrow light">READY WHEN YOU ARE</span><h2>What can we fix for you?</h2><p>Send your request today. We'll take it from there.</p></div><Link className="button button-light" to="/request">Request a repair <ArrowRight size={18} /></Link></div></section>
      </main>
      <footer className="public-footer"><div className="container"><div><strong>Prague HomeFix</strong><p>Reliable repairs for everyday homes.</p></div><div><small>Service hours</small><span>Mon–Fri: 08:00–18:00</span><span>Sat: 09:00–14:00</span></div><div><small>Contact</small><a href="tel:+420212345678">+420 212 345 678</a><a href="mailto:hello@praguehomefix.demo">hello@praguehomefix.demo</a></div><div><small>Portfolio demo</small><Link to="/demo">Open FlowLead CRM →</Link></div></div><p className="container copyright">© 2026 Prague HomeFix · Fictional business for portfolio demonstration</p></footer>
    </div>
  )
}
